
services:
  mysql:
    image: mysql:8.0
    env_file:
      - .env
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: eclipse-temurin:21-jre
    container_name: atm-app
    depends_on:
      mysql:
        condition: service_started
    env_file:
      - .env
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: mysql
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    volumes:
      - ./target/app.jar:/app/app.jar
      - ./target/classes:/app/classes
    working_dir: /app
    command: >
      sh -c "java -cp /app/app.jar:/app/classes
      -Dloader.path=/app/classes
      org.springframework.boot.loader.launch.JarLauncher"

volumes:
  mysql_data: