spring.application.name=CONF-OK
spring.datasource.url=${PROJECT_URL}

spring.datasource.username=${PROJECT_USER}
spring.datasource.password=${PROJECT_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
